# Generated by Django 6.0.2 on 2026-09-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcakepricing',
            options={'ordering': ['shape', 'tier', 'size', 'flavor']},
        ),
        migrations.RemoveConstraint(
            model_name='customcakepricing',
            name='unique_custom_cake_pricing',
        ),
        migrations.AddField(
            model_name='customcakepricing',
            name='shape',
            field=models.CharField(choices=[('round', 'Round'), ('rectangle', 'Rectangle')], default='round', max_length=20),
        ),
        migrations.AlterField(
            model_name='addonpricing',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='addonpricing',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='customcakepricing',
            constraint=models.UniqueConstraint(fields=('shape', 'tier', 'size', 'flavor'), name='unique_custom_cake_pricing'),
        ),
    ]
